# uncompyle6 version 3.9.3
# Python bytecode version base 3.6 (3379)
# Decompiled from: Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: client\render\shader\default_sprite.py
"""
Created on Apr 5, 2019

@author: Admin
"""
import sys, pyglet
from client.render.shader import Shader, ShaderProgram
vertex_shader = "\n#version 120\n\nvoid main()\n{\n    // transform the vertex position\n    gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\n\n    // transform the texture coordinates\n    gl_TexCoord[0] = gl_MultiTexCoord0;\n\n    // forward the vertex color\n    gl_FrontColor = gl_Color;\n}\n"
fragment_shader = "\n#version 120\n\nuniform sampler2D texture;\n\nvoid main()\n{\n    vec4 pixel = texture2D(texture, gl_TexCoord[0].xy);\n\n    gl_FragColor = gl_Color * pixel;\n}\n"
try:
    default_vert_shader = Shader(vertex_shader, "vertex")
except pyglet.gl.lib.MissingFunctionException as err:
    sys.stderr.write(str(err) + "\n")
    import ctypes
    ctypes.windll.user32.MessageBoxW(0, "Your OpenGL driver does not support required shader functionality.\nEnsure your graphics driver is up to date, and supported on your Operating System.", "OpenGL Check", 0)
    sys.exit(1)

default_frag_shader = Shader(fragment_shader, "fragment")
default_sprite_shader = ShaderProgram(default_vert_shader, default_frag_shader)
white_fragment_shader = "\n#version 120\n\nuniform sampler2D activeTexture;\n\nvoid main()\n{\n    // lookup the pixel in the texture\n    vec4 pixel = texture2D(activeTexture, gl_TexCoord[0].xy);\n    \n    pixel.rgb = vec3(1, 1, 1);\n\n    // make sprite all white, only usable for things like \n    gl_FragColor = gl_Color * pixel;\n}\n"
white_vert_shader = Shader(vertex_shader, "vertex")
white_frag_shader = Shader(white_fragment_shader, "fragment")
white_sprite_shader = ShaderProgram(white_vert_shader, white_frag_shader)
ripple_fragment_shader = "\n    #version 130\n    uniform float time;\n    uniform sampler2D activeTexture;\n\n    void main() {\n        vec2 uv = gl_TexCoord[0].xy;\n        \n        float X = uv.x*15.+time*3;\n        float Y = uv.y*15.+time*3;\n        \n        uv.x += sin(X-Y)*0.02*sin(Y);\n        uv.y += cos(X+Y)*0.02*cos(Y);\n        \n        gl_FragColor = texture(activeTexture, uv);\n    }\n"
ripple_frag = Shader(ripple_fragment_shader, "fragment")
ripple_shader = ShaderProgram(default_vert_shader, ripple_frag)
pulse_fragment_shader2 = "\nuniform float elapsed_time;\nuniform sampler2D activeTexture;\n\nvec2 location = vec2(1280, 720);\n\nvec3 hsb2rgb(in vec3 c)\n{\n    vec3 rgb = clamp(abs(mod(c.x*6.0+vec3(0.0,4.0,2.0),\n                             6.0)-3.0)-1.0,\n                     0.0,\n                     1.0 );\n    rgb = rgb*rgb*(3.0-2.0*rgb);\n    return c.z * mix( vec3(1.0), rgb, c.y);\n}\n\nvoid main()\n{   \n    vec2 p = (gl_TexCoord[0].xy);\n    float r = length(p)*.8;\n    r = r*2.-1.;\n    vec3 color = hsb2rgb(vec3(fract(elapsed_time*.1),.7,.4));\n    float s = sin(pow(r+1., 2.)-elapsed_time*3.+sin(r*.8))*sin(r+.99);\n    color *= (abs(1./(s*10.8))-.01);\n    gl_FragColor = vec4(color, 1.) * texture(activeTexture, p);\n}\n"
pulse_fragment_shader = "\nuniform float elapsed_time;\nuniform sampler2D activeTexture;\n\nfloat bell(float x, float center, float stretch) {\n    return exp(-pow((x - center) / stretch, 2.0));\n}\n\nvoid main()\n{\n    vec2 uv = gl_TexCoord[0].xy;\n    float x = abs((uv.x+0.5)*2.0)*abs((uv.x+0.5)*2.0);\n    float y = abs((uv.y)*2.0)*abs((uv.y)*2.0);\n        \n    vec4 col = texture(activeTexture, uv );\n    //vec3 a = fract(col.xyz + x+y-fract(elapsed_time));\n    \n    float r = col.x + fract(elapsed_time);\n    \n    gl_FragColor = vec4(r, col.y, col.z, 1.0);\n}\n\n\n"
pulse_frag_shader = Shader(pulse_fragment_shader, "fragment")
pulse_shader = ShaderProgram(default_vert_shader, pulse_frag_shader)
bubble_fragment_shader = "\n#version 120\n#define PI 3.1415926535\n#define TWOPI 2.0 * PI\n\nuniform float elapsed_time;\nuniform sampler2D activeTexture;\n    \nvoid main() {\n    vec2 uv = gl_TexCoord[0].xy;\n    \n    float X = uv.x*15.+elapsed_time*0.5;\n    float Y = uv.y*15.+elapsed_time*0.5;\n    \n    uv.x += sin(X-Y)*0.01*sin(Y);\n    uv.y += cos(X+Y)*0.01*cos(Y);\n    \n    gl_FragColor = texture2D(activeTexture, uv);\n}\n"
bubble_frag_shader = Shader(bubble_fragment_shader, "fragment")
bubble_shader = ShaderProgram(default_vert_shader, bubble_frag_shader)
shield_fragment_shader = "\n#version 120\n\nuniform float elapsed_time;\nuniform sampler2D mask;\nuniform sampler2D effect;\n\n\nvoid main()\n{\n    // lookup the pixel in the texture\n    //vec4 pixel = mix(texture2D(mask, gl_TexCoord[0].xy), texture2D(activeTexture2, gl_TexCoord[0].xy), 0.9);\n    \n    //vec4 distort = texture2D(mask, gl_TexCoord[0].xy);\n    \n    //vec4 pixel = texture2D(activeTexture2, vec2(gl_TexCoord[0].xy - (distort.gb - 0.5)));\n    \n    vec2 uv = gl_TexCoord[0].xy;\n    \n    vec2 warpUV = 6. * gl_TexCoord[0].xy;\n    \n    float d = length( warpUV );\n    \n    //vec4 color = texture2D(noise, warpUV);\n    \n    vec2 st = warpUV*0.1 + 0.2*vec2(cos(0.071*elapsed_time*8.+d),\n                                sin(0.073*elapsed_time*8.-d));\n\n    vec4 color = texture2D( effect, st );\n    \n    vec4 mask = texture2D(mask, uv);\n\n    \n    // multiply it by the color\n    \n    \n    gl_FragColor = vec4(color * mask.a);\n}\n"
shield_alternate_fragment = "\n#version 120\n\nuniform float elapsed_time;\nuniform sampler2D mask;\nuniform sampler2D effect;\n\n\nconst float PI = 3.14159265;\n\nfloat sphere(float t, float k)\n{\n    float d = 1.0+t*t-t*t*k*k;\n    if (d <= 0.0)\n        return -1.0;\n    float x = (k - sqrt(d))/(1.0 + t*t);\n    return asin(x*t);\n}\n\n\nvoid main()\n{\n    // bg texture\n    \n    \n      vec2 uv = gl_TexCoord[0].xy;\n    //float v = iResolution.x / iResolution.y;\n    uv /= 1.3;\n\n    float len = length(uv);\n    float k = 1.0;\n    float len2;\n\n    len2 = sphere(len*k,sqrt(2.0))/sphere(1.0*k,sqrt(2.0));\n    uv = uv * len2 * 0.5 / len;\n    uv = uv + 0.5;\n\n    \n    vec2 pos = uv;\n    float t = elapsed_time/1.0;\n    float scale1 = 40.0;\n    float scale2 = 20.0;\n    float val = 0.0;\n    \n    val += sin((pos.x*scale1 + t));\n    val += sin((pos.y*scale1 + t)/2.0);\n    val += sin((pos.x*scale2 + pos.y*scale2 + sin(t))/2.0);\n    val += sin((pos.x*scale2 - pos.y*scale2 + t)/2.0);\n    val /= 2.0;\n    \n    float glow = 0.020 / (0.015 + distance(len, 1.0));\n    \n    vec4 amask = texture2D(mask, gl_TexCoord[0].xy );\n    \n    val = (cos(PI*val) + 1.0) * 0.5;\n    vec4 col2 = vec4(0.6, 0.7, 1.0, 1.0);\n    \n    vec4 texColor = texture2D(effect, uv * val * step(len, 1.0));\n    \n    gl_FragColor = texColor * amask.a  * col2;\n    \n    //gl_FragColor = step(len, 1.0) * 0.5 * col2 * val + glow * col2 + 0.5 * texColor * amask.a;\n}\n\n\n"
shield_frag_shader = Shader(shield_alternate_fragment, "fragment")
shield_shader = ShaderProgram(default_vert_shader, shield_frag_shader)
crystal_fragment_shader3 = "\n#version 150\n\nuniform sampler2D crystalTexture;\nuniform float iTime;\n\nmat4 saturationMatrix( float saturation ) {\n    vec3 luminance = vec3( 0.3086, 0.6094, 0.0820 );\n    float oneMinusSat = 1.0 - saturation;\n    vec3 red = vec3( luminance.x * oneMinusSat );\n    red.r += saturation;\n    \n    vec3 green = vec3( luminance.y * oneMinusSat );\n    green.g += saturation;\n    \n    vec3 blue = vec3( luminance.z * oneMinusSat );\n    blue.b += saturation;\n    \n    return mat4( \n        red,     0,\n        green,   0,\n        blue,    0,\n        0, 0, 0, 1 );\n}\n\nvec4 shiftHue(in vec3 col, in float Shift)\n{\n    vec3 P = vec3(0.55735) * dot(vec3(0.55735), col);\n    vec3 U = col - P;\n    vec3 V = cross(vec3(0.55735), U);    \n    col = U * cos(Shift * 6.2832) + V * sin(Shift * 6.2832) + P;\n    return vec4(col, 1.0);\n}\n\nvoid main()\n{\n    float brightness = 0.15;\n    float contrast = 1.2;\n    float saturation = 1.2;\n    float _vibrance = 4.0;\n    float _hue = abs(sin(iTime * 0.001)); \n    \n    vec2 uv = gl_TexCoord[0].xy;\n    \n    vec4 color = texture2D( crystalTexture, uv );\n    \n    gl_FragColor = saturationMatrix(saturation) * color; \n    gl_FragColor = shiftHue(gl_FragColor.rgb, _hue);\n    gl_FragColor.a = 1.0;\n    gl_FragColor *= color;\n}\n"
crystal_fragment_shader = "\n#version 120\n\nuniform sampler2D crystalTexture;\nuniform float iTime;\n\nvec3 hs(vec3 c, float s){\n    vec3 m=vec3(cos(s),s=sin(s)*.5774,-s);\n    return c*mat3(m+=(1.-m.x)/3.,m.zxy,m.yzx);\n}\n\nvoid main()\n{\n    vec2 uv = gl_TexCoord[0].xy;\n\n    vec4 col = texture2D( crystalTexture, uv );\n    \n    gl_FragColor = vec4(hs(col.rgb, iTime * 0.001), 1.) * col;\n}\n"
ray_frag_shader = "\n#version 130\nuniform float iTime;\n\nfloat angle = 0.7;\nfloat position = 0.2;\nfloat spread = 0.5;\nfloat cutoff = 0.1;\nfloat falloff = 0.3;\nfloat edge_fade = 0.15;\n\nfloat speed = 200.0;\nfloat ray1_density = 38.0;\nfloat ray2_density = 30.0;\nfloat ray2_intensity = 0.3;\n\nvec4 color = vec4(1.0, 0.9, 0.65, 0.8);\n\nbool hdr = false;\nfloat seed = 5.0;\n\n// Random and noise functions from Book of Shader's chapter on Noise.\nfloat random(vec2 _uv) {\n    return fract(sin(dot(_uv.xy,\n                         vec2(12.9898, 78.233))) *\n        43758.5453123);\n}\n\nfloat noise (in vec2 uv) {\n    vec2 i = floor(uv);\n    vec2 f = fract(uv);\n\n    // Four corners in 2D of a tile\n    float a = random(i);\n    float b = random(i + vec2(1.0, 0.0));\n    float c = random(i + vec2(0.0, 1.0));\n    float d = random(i + vec2(1.0, 1.0));\n\n\n    // Smooth Interpolation\n\n    // Cubic Hermine Curve. Same as SmoothStep()\n    vec2 u = f * f * (3.0-2.0 * f);\n\n    // Mix 4 coorners percentages\n    return mix(a, b, u.x) +\n            (c - a)* u.y * (1.0 - u.x) +\n            (d - b) * u.x * u.y;\n}\n\nmat2 rotate(float _angle){\n    return mat2(vec2(cos(_angle), -sin(_angle)),\n                vec2(sin(_angle), cos(_angle)));\n}\n\nvec4 screen(vec4 base, vec4 blend){\n    return 1.0 - (1.0 - base) * (1.0 - blend);\n}\n\nvoid main()\n{\n    // Normalized pixel coordinates (from 0 to 1)\n    vec2 uv = gl_TexCoord[0].xy;\n    \n    // Rotate, skew and move the UVs\n    vec2 transformed_uv = ( rotate(angle) * (uv - position) )  / ( (uv.y + spread) - (uv.y * spread) );\n    \n    // Animate the ray according the the new transformed UVs\n    vec2 ray1 = vec2(transformed_uv.x * ray1_density + sin(iTime * 0.1 * speed) * (ray1_density * 0.2) + seed, 1.0);\n    vec2 ray2 = vec2(transformed_uv.x * ray2_density + sin(iTime * 0.2 * speed) * (ray1_density * 0.2) + seed, 1.0);\n    \n    // Cut off the ray's edges\n    float cut = step(cutoff, transformed_uv.x) * step(cutoff, 1.0 - transformed_uv.x);\n    ray1 *= cut;\n    ray2 *= cut;\n    \n    // Apply the noise pattern (i.e. create the rays)\n    float rays;\n    \n    if (hdr){\n        // This is not really HDR, but check this to not clamp the two merged rays making \n        // their values go over 1.0. Can make for some nice effect\n        rays = noise(ray1) + (noise(ray2) * ray2_intensity);\n    }\n    else{\n         rays = clamp(0., 1., noise(ray1) + (noise(ray2) * ray2_intensity));\n    }\n    \n    // Fade out edges\n    rays *= smoothstep(0.0, falloff, uv.y); // Bottom\n    rays *= smoothstep(0.0 + cutoff, edge_fade + cutoff, transformed_uv.x); // Left\n    rays *= smoothstep(0.0 + cutoff, edge_fade + cutoff, 1.0 - transformed_uv.x); // Right\n    \n    // Color to the rays\n    vec3 shine = vec3(rays) * color.rgb;\n    \n    // Output to screen\n    gl_FragColor = vec4(shine, rays * color.a);\n}\n"
aurora_frag_shader = "\nuniform float iTime;\nuniform sampler2D activeTexture;\n\nconst bool leftToRight = false;\nfloat slopeSign = (leftToRight ? -1.0 : 1.0);\nfloat slope1 = 5.0 * slopeSign;\nfloat slope2 = 7.0 * slopeSign;\t\n\nvoid main()\n{\n    vec2 uv = gl_TexCoord[0].xy;\n\n    iTime *= 0.001;\n\n    float bright = \n    - sin(uv.y * slope1 + uv.x * 30.0+ iTime *3.10) *.2 \n    - sin(uv.y * slope2 + uv.x * 37.0 + iTime *3.10) *.1\n    - cos(              + uv.x * 2.0 * slopeSign + iTime *2.10) * 0.1 \n    - sin(              - uv.x * 5.0 * slopeSign + iTime * 2.0) * 0.3;\n\n    float modulate = abs(cos(iTime*.1) *.5 + sin(iTime * .7)) * 0.4;\n\n    bright *= modulate;\n    vec4 pix = texture2D(activeTexture,uv);\n\n    pix.rgb += clamp(bright / 1.0,0.0,1.0);\n\n    gl_FragColor = pix;\n}\n"
outline_frag = "\n#define PI 3.14159265359\n#define SAMPLES 2\n#define MAG 0.02\n\nuniform sampler2D activeTexture;\n\nvoid main()\n{\n    vec2 uv = gl_TexCoord[0].xy;\n    //Animate the cat\n    //uv.x /= 6.0;\n    //uv.x += (0.15625 * mod(floor(iTime * 10.0), 6.0));\n    //uv.x -= 0.01;\n    //----------------\n    \n    vec3 targetCol = vec3(0.5, 0.5, 1.0); //The color of the outline\n    \n    vec4 finalCol = vec4(0);\n    \n    float rads = ((360.0 / float(SAMPLES)) * PI) / 180.0;\t//radians based on SAMPLES\n    \n    for(int i = 0; i < SAMPLES; i++)\n    {\n        if(finalCol.w < 0.1)\n        {\n            float r = float(i + 1) * rads;\n            vec2 offset = vec2(cos(r) * 0.1, -sin(r)) * MAG; //calculate vector based on current radians and multiply by magnitude\n            finalCol = texture(activeTexture, uv + offset);\t//render the texture to the pixel on an offset UV\n            if(finalCol.w > 0.0)\n            {\n                finalCol.xyz = targetCol;\n            }\n        }\n    }\n    \n    vec4 tex = texture(activeTexture, uv);\n    if(tex.w > 0.0)\n    {\n        finalCol = tex;   //if the centered texture's alpha is greater than 0, set finalcol to tex\n    }\n    \n    gl_FragColor = finalCol;\n}\n"
lightray_fragment_shader = "\n#version 130\n\nuniform sampler2D texture; // Texture to which we'll apply our shader? (should its name be u_texture?)\nuniform float time;\n\nfloat frequency = 1.0;\nfloat amplitude = 0.05;\nfloat angle = 1.0;\nfloat spread = 0.5;\nfloat speed = 3.0;\nfloat ray1_density = 8.2;\nfloat ray2_density = 25.0;\nfloat ray2_intensity = 0.3;\nfloat seed = 0.4;\n\n\n\nhighp float rand(vec2 co)\n{\n    highp float a = 12.9898;\n    highp float b = 78.233;\n    highp float c = 43758.5453;\n    highp float dt= dot(co.xy ,vec2(a,b));\n    highp float sn= mod(dt,3.14);\n    return fract(sin(sn) * c);\n}\n\nfloat noise (in vec2 uv) {\n    vec2 i = floor(uv);\n    vec2 f = fract(uv);\n\n    // Four corners in 2D of a tile\n    float a = rand(i);\n    float b = rand(i + vec2(1.0, 0.0));\n    float c = rand(i + vec2(0.0, 1.0));\n    float d = rand(i + vec2(1.0, 1.0));\n\n\n    // Smooth Interpolation\n\n    // Cubic Hermine Curve. Same as SmoothStep()\n    vec2 u = f * f * (3.0-2.0 * f);\n\n    // Mix 4 coorners percentages\n    return mix(a, b, u.x) +\n            (c - a)* u.y * (1.0 - u.x) +\n            (d - b) * u.x * u.y;\n}\n\nmat2 rotate(float _angle){\n    return mat2(vec2(cos(_angle), -sin(_angle)),\n                vec2(sin(_angle), cos(_angle)));\n}\n\nvoid main()\n{\n    vec2 uv = gl_TexCoord[0].xy;\n\n    vec2 transformed_uv = ( rotate(angle) * (uv) )  / ( (uv.y + spread) - (uv.y * spread) );\n\n    // Animate the ray according the the new transformed UVs\n    vec2 ray1 = vec2(transformed_uv.x * ray1_density + sin(time * 0.1 * speed) * (ray1_density * 0.2) + seed, 1.0);\n    vec2 ray2 = vec2(transformed_uv.x * ray2_density + sin(time * 0.2 * speed) * (ray1_density * 0.2) + seed, 1.0);\n    \n    float rays = clamp(noise(ray1) + (noise(ray2) * ray2_intensity), 0.0, 1.);\n    \n    vec4 color = texture2D(texture, uv);\n    \n    color.a *= rays;\n\n    gl_FragColor = color;\n}\n"
lightray_vert_shader = Shader(vertex_shader, "vertex")
lightray_frag_shader = Shader(lightray_fragment_shader, "fragment")
lightray_shader = ShaderProgram(lightray_vert_shader, lightray_frag_shader)
