# uncompyle6 version 3.9.3
# Python bytecode version base 3.6 (3379)
# Decompiled from: Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: client\data\utils\anchor.py
"""
Created on 25 juil. 2011

@author: Kami
"""

class AnchorType:
    TOP = 1
    _TOP_FIXED = 2
    BOTTOM = 4
    _BOTTOM_FIXED = 8
    LEFT = 16
    _LEFT_FIXED = 32
    RIGHT = 64
    _RIGHT_FIXED = 128
    CENTERX = 256
    _CENTERX_FIXED = 512
    CENTERY = 1024
    _CENTERY_FIXED = 2048
    TOPLEFT = TOP + _LEFT_FIXED
    TOPRIGHT = TOP + _RIGHT_FIXED
    TOPCENTER = TOP + _CENTERX_FIXED
    BOTTOMLEFT = BOTTOM + _LEFT_FIXED
    BOTTOMRIGHT = BOTTOM + _RIGHT_FIXED
    BOTTOMCENTER = BOTTOM + _CENTERX_FIXED
    LEFTTOP = LEFT + _TOP_FIXED
    LEFTBOTTOM = LEFT + _BOTTOM_FIXED
    LEFTCENTER = LEFT + _CENTERY_FIXED
    RIGHTTOP = RIGHT + _TOP_FIXED
    RIGHTBOTTOM = RIGHT + _BOTTOM_FIXED
    RIGHTCENTER = RIGHT + _CENTERY_FIXED
    CENTERLEFT = CENTERY + _LEFT_FIXED
    CENTERRIGHT = CENTERY + _RIGHT_FIXED
    CENTERTOP = CENTERX + _TOP_FIXED
    CENTERBOTTOM = CENTERX + _BOTTOM_FIXED
    CENTERXCENTER = CENTERX + _CENTERY_FIXED
    CENTERYCENTER = CENTERY + _CENTERX_FIXED
    CENTER = _CENTERY_FIXED + _CENTERX_FIXED
    TOPCENTERFIXED = _CENTERX_FIXED + _TOP_FIXED
    BOTTOMCENTERFIXED = _CENTERX_FIXED + _BOTTOM_FIXED
    TOPLEFTFIXED = _TOP_FIXED + _LEFT_FIXED
    TOPRIGHTFIXED = _TOP_FIXED + _RIGHT_FIXED
    BOTTOMRIGHTFIXED = _BOTTOM_FIXED + _RIGHT_FIXED
    BOTTOMLEFTFIXED = _BOTTOM_FIXED + _LEFT_FIXED
    ALL_NORMAL = [
     TOP, LEFT, RIGHT, BOTTOM, CENTERX, CENTERY]
    ALL_FIXED = [_TOP_FIXED, _LEFT_FIXED, _RIGHT_FIXED, _BOTTOM_FIXED, _CENTERX_FIXED, _CENTERY_FIXED]
    ALL_VERTICAL = [TOP, _TOP_FIXED, BOTTOM, _BOTTOM_FIXED, CENTERY, _CENTERY_FIXED]
    ALL_HORIZONTAL = [LEFT, _LEFT_FIXED, RIGHT, _RIGHT_FIXED, CENTERX, _CENTERX_FIXED]
    VERTICAL = [TOP, BOTTOM, CENTERY]
    HORIZONTAL = [LEFT, RIGHT, CENTERX]
    VERTICAL_LINKS = [_CENTERX_FIXED, _LEFT_FIXED, _RIGHT_FIXED]
    HORIZONTAL_LINKS = [_CENTERY_FIXED, _TOP_FIXED, _BOTTOM_FIXED]
    HORIZONTAL_STACKABLE = [LEFTTOP, LEFTBOTTOM, LEFTCENTER, RIGHTTOP, RIGHTBOTTOM, RIGHTCENTER, CENTERTOP, 
     CENTERBOTTOM, CENTERXCENTER]
    VERTICAL_STACKABLE = [TOPLEFT, TOPRIGHT, TOPCENTER, BOTTOMLEFT, BOTTOMRIGHT, BOTTOMCENTER, CENTERLEFT, 
     CENTERYCENTER, CENTERRIGHT]
    toStr = {TOP: "TOP", 
     _TOP_FIXED: "TOPFIXED", 
     LEFT: "LEFT", 
     _LEFT_FIXED: "LEFTFIXED", 
     BOTTOM: "BOTTOM", 
     _BOTTOM_FIXED: "BOTTOMFIXED", 
     RIGHT: "RIGHT", 
     _RIGHT_FIXED: "RIGHTFIXED", 
     CENTERX: "CENTERX", 
     _CENTERX_FIXED: "CENTERXFIXED", 
     CENTERY: "CENTERY", 
     _CENTERY_FIXED: "CENTERYFIXED"}


class Alignment:
    NONE = "none"
    LEFT = "left"
    CENTER = "center"
    RIGHT = "right"


class Align:
    VERTICAL = 1
    HORIZONTAL = 2
