# uncompyle6 version 3.9.3
# Python bytecode version base 3.6 (3379)
# Decompiled from: Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: client\data\world\skill.py
"""
Created on Jul 26, 2011

@author: Ragnarok
"""
import time
from shared.container.skill import SkillUseInstance

class ClientSkillUseInstance(SkillUseInstance):

    @staticmethod
    def callAgain(classObject, skillInfo, damageType, char, atkChar=None, instanceId=None):
        classObject(skillInfo, damageType, char, atkChar, instanceId)

    def onDamageSourceReceived(self, targetId, targetIdRange, x, y, z, direction, radius, duration, timeStamp):
        """Used to tell if a skill generated extra effects.
        Examples: Magnitude generates random points of falling rocks. These are generated by server.
        String Shot: Even though we lower stat of player, we still want an effect that it hit player."""
        return

    def onPositionUpdate(self, x, y):
        return
